import React,{useState} from 'react';
import {afterEach,describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import Sections,{DailyPersonEditor} from '../components/SurveyFieldSections';
import Evidence from '../components/SurveyEvidence';
import {blankSimpleSurvey,makers,normalizeSurvey,type SimpleSurveyData} from '../lib/simple-survey';
import {surveyDirectory,csvCell} from '../lib/survey-directory';
import {reportSections,reportLines} from '../lib/survey-report-model';
const storage=vi.hoisted(()=>({upload:vi.fn(async()=>({error:null})),createSignedUrl:vi.fn()}));
vi.mock('../lib/supabase',()=>({supabase:{storage:{from:()=>storage}}}));
afterEach(cleanup);
function Harness({step,initial=blankSimpleSurvey('Kerala')}:{step:number;initial?:SimpleSurveyData}){const [data,setData]=useState(initial);return <Sections step={step} data={data} set={setData}/>}
describe('Field survey release',()=>{
 it('starts with one Organization and switches only the selected gathering while retaining its data',()=>{render(<Harness step={3}/>);expect(screen.getAllByLabelText('Organization Name')).toHaveLength(1);expect(screen.queryByText('Sabha Details')).toBeNull();fireEvent.change(screen.getByLabelText('Type of Gathering'),{target:{value:'Mahasabha'}});fireEvent.change(screen.getByLabelText('Venue Name'),{target:{value:'Main ground'}});fireEvent.change(screen.getByLabelText('Type of Gathering'),{target:{value:'None'}});expect(screen.queryByLabelText('Venue Name')).toBeNull();fireEvent.change(screen.getByLabelText('Type of Gathering'),{target:{value:'Mahasabha'}});expect((screen.getByLabelText('Venue Name') as HTMLInputElement).value).toBe('Main ground');fireEvent.click(screen.getByRole('button',{name:'+ Add Organization'}));expect(screen.getAllByLabelText('Organization Name')).toHaveLength(2);});
 it('keeps existing drafts and legacy logistics during additive normalization',()=>{const d=blankSimpleSurvey('Kerala');d.organizations[0].sabha.venueName='Old venue';const normalized=normalizeSurvey(d);expect(normalized.organizations[0].id).toBe(d.organizations[0].id);expect(normalized.organizations[0].sabha.venueName).toBe('Old venue');expect(normalized.committees.local).toEqual([]);render(<Harness step={3} initial={normalized}/>);expect((screen.getByLabelText('Type of Gathering') as HTMLSelectElement).value).toBe('Sabha');});
 it('offers independent contacts and preserves the requested field order',()=>{const d=blankSimpleSurvey('Kerala'),p=makers.person();render(<DailyPersonEditor person={p} data={d} dayId="day" onChange={vi.fn()}/>);const labels=Array.from(document.querySelectorAll('label > span')).map(x=>x.textContent);expect(labels.slice(0,5)).toEqual(['Name','Mobile Number','Organization Name','Other Contact Number','Remarks / Reference Point']);expect(screen.getByRole('option',{name:'No Organization / Individual'})).toBeTruthy();});
 it('exports new route, local committee and contact details without private storage paths',()=>{const d=blankSimpleSurvey('Kerala'),day=makers.daily();day.persons=[{...makers.person(),name:'Coordinator',mobile:'9990000000',organizationId:d.organizations[0].id}];d.organizations[0].name='Ashram';d.dailyLogs=[day];d.committees.local=[{...makers.member(),nameDesignation:'Local head',role:'Convenor'}];d.finalRoute=[{...makers.route(),recommendation:'Inspect bridge before approval'}];const text=reportSections(d).flatMap(x=>reportLines(x.value)).join('\n');expect(text).toContain('Convenor');expect(text).toContain('Inspect bridge before approval');expect(text).toContain('9990000000');expect(surveyDirectory(d).find(x=>x.name==='Coordinator')?.context).toContain('Ashram');expect(csvCell(' =HYPERLINK("bad")')).toMatch(/^"'/);});
 it('links camera/map uploads to the right record and emits only new references',async()=>{Object.defineProperty(navigator,'onLine',{value:true,configurable:true});const add=vi.fn();render(<Evidence data={blankSimpleSurvey('Kerala')} assignmentId="assignment" userId="user" onAdd={add} entityId="halt-1" entityLabel="Major Halt" maps/>);expect(screen.getByLabelText('Take Photo').getAttribute('capture')).toBe('environment');fireEvent.change(screen.getByLabelText('Attach Map / Upload Route Map'),{target:{files:[new File(['map'],'route.pdf',{type:'application/pdf'})]}});await waitFor(()=>expect(add).toHaveBeenCalledOnce());expect(add.mock.calls[0][0][0]).toMatchObject({entityId:'halt-1',entityLabel:'Major Halt',kind:'map',name:'route.pdf'});});
});
