import React from 'react';
import {describe,it,expect,vi,afterEach} from 'vitest';
import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import {blankSimpleSurvey,makers} from '../lib/simple-survey';
import {reportSections,reportLines} from '../lib/survey-report-model';
import SurveyReport from '../components/SurveyReport';
vi.mock('../lib/simple-report',()=>({downloadSimpleSurveyPdf:vi.fn(),downloadDailySurveyPdf:vi.fn()}));
afterEach(cleanup);
const fixture=()=>{const d=blankSimpleSurvey('Rajasthan');const later=makers.daily(2),first=makers.daily(1);first.date='2026-09-10';first.findings='समन्वय बैठक पूरी हुई';later.findings='Day two findings';d.dailyLogs=[later,first];const o=makers.organization('Rajasthan');o.name='Test Ashram';o.nightHalt.otherConsiderations='Wheelchair access inspected';o.mahaRath.localCoordination='Contact the coordinator';o.contacts=[{...makers.contact(),name:'Test contact',remarks:'Evening calls only'}];d.organizations=[o];const m=makers.member();m.cityState='City and State';m.cityDistrict='City and District';m.districtAddress='Full district address';d.committees.national=[m];d.attachments=[{id:'secret-id',path:'private/path/never-export',name:'visit-evidence.jpg',size:1500,type:'image/jpeg',dayId:first.id,uploadedAt:'2026-09-10'}];return d;};
describe('Detailed survey reports',()=>{
 it('preserves nested details and all committee fields, excludes private paths, and sorts days without mutating data',()=>{const d=fixture();const sections=reportSections(d,{status:'submitted',revision:4,submittedAt:'2026-09-10T10:00:00Z'});const text=sections.flatMap(s=>reportLines(s.value)).join('\n');for(const v of ['Wheelchair access inspected','Evening calls only','City and State','City and District','Full district address','visit-evidence.jpg','submitted','समन्वय बैठक पूरी हुई'])expect(text).toContain(v);expect(text).not.toContain('private/path');expect(text).not.toContain('secret-id');const days=sections.find(s=>s.title.includes('Daily Activity'))!.value as any[];expect(days.map(d=>d.dayNo)).toEqual([1,2]);expect(d.dailyLogs.map(d=>d.dayNo)).toEqual([2,1]);});
 it('daily report includes only the requested day and linked evidence',()=>{const d=fixture();const sections=reportSections(d,{},d.dailyLogs[1].id);const text=sections.flatMap(s=>reportLines(s.value)).join('\n');expect(text).toContain('समन्वय बैठक पूरी हुई');expect(text).toContain('visit-evidence.jpg');expect(text).not.toContain('Day two findings');expect(sections.some(s=>s.title.includes('Organizations'))).toBe(false);});
 it('keeps the full report accessible after submission and prints in the current page without pop-ups',()=>{const print=vi.spyOn(window,'print').mockImplementation(()=>{});render(<SurveyReport data={fixture()} meta={{status:'submitted',revision:4}}/>);expect(screen.getByText('Your completed survey report')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'View detailed report'}));expect(screen.getByRole('dialog')).toBeTruthy();expect(screen.getByText('Wheelchair access inspected')).toBeTruthy();expect(screen.getByText('समन्वय बैठक पूरी हुई')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Print / Save PDF'}));expect(print).toHaveBeenCalledOnce();fireEvent.keyDown(document,{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(document.body.style.overflow).toBe('');});
});
