'use client';
import {createContext,useContext,useRef,useState} from 'react';
import {supabase} from '@/lib/supabase';
import type {SimpleSurveyData,SurveyAttachment} from '@/lib/simple-survey';
import s from './SimpleSurvey.module.css';
const bucket='simple-survey-evidence';
type Props={data:SimpleSurveyData;assignmentId:string;userId:string;onChange?:(files:SurveyAttachment[])=>void;onAdd?:(files:SurveyAttachment[])=>void;readOnly?:boolean;entityId?:string;entityLabel?:string;day?:string;maps?:boolean;onBusy?:(busy:boolean)=>void};
const EvidenceContext=createContext<Omit<Props,'entityId'|'entityLabel'>|null>(null);
export const EvidenceProvider=EvidenceContext.Provider;
export function EntityEvidence(props:{entityId:string;entityLabel:string;day?:string;maps?:boolean}){const context=useContext(EvidenceContext);return context?<SurveyEvidence {...context} {...props}/>:null;}
export default function SurveyEvidence({data,assignmentId,userId,onChange,onAdd,readOnly=false,entityId,entityLabel,day='',maps=false,onBusy}:Props){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dayId,setDayId]=useState(day);const latest=useRef(data);latest.current=data;
 const upload=async(event:React.ChangeEvent<HTMLInputElement>,kind:SurveyAttachment['kind'])=>{const files=Array.from(event.target.files||[]);event.target.value='';if(!files.length)return;if(!navigator.onLine){setMessage('Uploads need internet. Keep the photo or map on your device and attach it when online.');return;}setBusy(true);onBusy?.(true);const added:SurveyAttachment[]=[];try{for(const file of files){if(file.size>20*1024*1024)throw new Error(`${file.name} exceeds the 20 MB limit.`);const path=`${userId}/${assignmentId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;added.push({id:crypto.randomUUID(),path,name:file.name,size:file.size,type:file.type,dayId:day||dayId,entityId,entityLabel,kind,uploadedAt:new Date().toISOString()});}setMessage('Uploaded privately. The survey will sync these files.');}catch(e:any){setMessage(e.message);}finally{if(added.length){if(onAdd)onAdd(added);else onChange?.([...(latest.current.attachments||[]),...added]);}setBusy(false);onBusy?.(false);}};
 const open=async(file:SurveyAttachment)=>{setMessage('');const {data:link,error}=await supabase.storage.from(bucket).createSignedUrl(file.path,120);if(error){setMessage(error.message);return;}const a=document.createElement('a');a.href=link.signedUrl;a.target='_blank';a.rel='noopener noreferrer';a.click();};
 return <div className={s.miniPanel} style={{marginTop:16}}><h4>{entityId?'Photo & evidence':'Photos & supporting documents'}</h4>{!readOnly&&<>{!entityId&&<label className={s.field}><span>Link files to</span><select value={dayId} onChange={e=>setDayId(e.target.value)}><option value="">Overall State survey</option>{data.dailyLogs.map(d=><option key={d.id} value={d.id}>Day {d.dayNo} · {d.date||'Undated'}</option>)}</select></label>}<div className={s.grid2}><label className={s.field}><span>Upload Photo</span><input type="file" multiple disabled={busy} accept="image/*" onChange={e=>upload(e,'photo')}/></label><label className={s.field}><span>Take Photo</span><input type="file" disabled={busy} accept="image/*" capture="environment" onChange={e=>upload(e,'photo')}/></label>{(maps||!entityId)&&<label className={s.field}><span>{maps?'Attach Map / Upload Route Map':'Attach supporting document'}</span><input type="file" multiple disabled={busy} accept="image/*,.pdf,.doc,.docx" onChange={e=>upload(e,maps?'map':'document')}/></label>}</div><small>Optional · private uploads · internet required · maximum 20 MB per file</small></>}{busy&&<p role="status">Uploading…</p>}{message&&<p role="status">{message}</p>}{(data.attachments||[]).filter(f=>!entityId||f.entityId===entityId).map(file=><div className={s.readItem} key={file.id}><button type="button" className={s.secondary} onClick={()=>open(file)}>{file.name}</button><p>{file.entityLabel||'State survey'} · {file.kind||'document'} · {Math.ceil(file.size/1024)} KB</p></div>)}</div>;
}
