'use client';
import {useState} from 'react';
import {supabase} from '@/lib/supabase';
import type {SimpleSurveyData,SurveyAttachment} from '@/lib/simple-survey';
import s from './SimpleSurvey.module.css';
const bucket='simple-survey-evidence';
export default function SurveyEvidence({data,assignmentId,userId,onChange,readOnly=false}:{data:SimpleSurveyData;assignmentId:string;userId:string;onChange?:(files:SurveyAttachment[])=>void;readOnly?:boolean}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dayId,setDayId]=useState('');
 const upload=async(event:React.ChangeEvent<HTMLInputElement>)=>{const files=Array.from(event.target.files||[]);event.target.value='';if(!navigator.onLine){setMessage('File uploads need an internet connection. Keep the files on your device and attach them when online.');return;}setBusy(true);const added:SurveyAttachment[]=[];try{for(const file of files){if(file.size>20*1024*1024)throw new Error(`${file.name} exceeds the 20 MB limit.`);const path=`${userId}/${assignmentId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;added.push({id:crypto.randomUUID(),path,name:file.name,size:file.size,type:file.type,dayId,uploadedAt:new Date().toISOString()});}setMessage('Files uploaded privately. Save the survey to sync their references.');}catch(e:any){setMessage(e.message);}finally{if(added.length)onChange?.([...(data.attachments||[]),...added]);setBusy(false);}};
 const open=async(file:SurveyAttachment)=>{setMessage('');const {data:link,error}=await supabase.storage.from(bucket).createSignedUrl(file.path,120);if(error){setMessage(error.message);return;}const a=document.createElement('a');a.href=link.signedUrl;a.target='_blank';a.rel='noopener noreferrer';a.click();};
 return <section className={s.sectionCard} style={{marginTop:16}}><h3>Photos & supporting documents</h3><p>Private attachments · photos, PDF/Word reports, audio or video · up to 20 MB per file.</p>{!readOnly&&<><label className={s.field}><span>Link files to</span><select value={dayId} onChange={e=>setDayId(e.target.value)}><option value="">Overall State survey / final report</option>{data.dailyLogs.map(d=><option key={d.id} value={d.id}>Day {d.dayNo} · {d.date||'Undated'}</option>)}</select></label><label className={s.field}><span>Attach files (internet required)</span><input type="file" multiple disabled={busy} accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx,.mp3,.m4a,.wav,.webm,.mp4" onChange={upload}/></label></>}{busy&&<p role="status">Uploading…</p>}{message&&<p role="status">{message}</p>}{(data.attachments||[]).map(file=><div className={s.readItem} key={file.id}><button type="button" className={s.secondary} onClick={()=>open(file)}>{file.name}</button><p>{Math.ceil(file.size/1024)} KB · {data.dailyLogs.find(d=>d.id===file.dayId)?`Day ${data.dailyLogs.find(d=>d.id===file.dayId)!.dayNo}`:'State survey'} · {new Date(file.uploadedAt).toLocaleString()}</p></div>)}</section>;
}
